# Generated by Django 2.2.1 on 2019-09-17 22:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RaceEvent',
            fields=[
                ('fis_id', models.IntegerField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=50)),
                ('discipline', models.CharField(max_length=20)),
                ('race_date', models.DateTimeField()),
                ('cancelled', models.BooleanField(default=False)),
                ('tips_published', models.BooleanField(default=False)),
                ('points_multiplier', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Racer',
            fields=[
                ('fis_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tipp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('alle_im_ziel', models.BooleanField(default=False)),
                ('comment', models.TextField()),
                ('dnf', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='dnfs', to='skitipp.Racer')),
                ('place_1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='place_1', to='skitipp.Racer')),
                ('place_2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='place_2', to='skitipp.Racer')),
                ('place_3', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='place_3', to='skitipp.Racer')),
                ('race_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skitipp.RaceEvent')),
                ('tipper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RaceCompetitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_number', models.IntegerField()),
                ('rank', models.IntegerField(null=True)),
                ('is_dnf', models.BooleanField(default=False)),
                ('race_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_list', to='skitipp.RaceEvent')),
                ('racer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='start_lists', to='skitipp.Racer')),
            ],
        ),
    ]
