# Generated by Django 2.2.1 on 2019-09-17 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skitipp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipp',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
