# Generated by Django 2.2.1 on 2019-09-17 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skitipp', '0002_auto_20190918_0052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='raceevent',
            old_name='discipline',
            new_name='kind',
        ),
    ]
