# Generated by Django 2.2.1 on 2019-09-17 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skitipp', '0006_auto_20190918_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipp',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
