# Generated by Django 2.2.1 on 2019-09-18 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skitipp', '0008_auto_20190918_0831'),
    ]

    operations = [
        migrations.CreateModel(
            name='TippPointTally',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.FloatField()),
                ('race_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_tally', to='skitipp.RaceEvent')),
                ('tipp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='points_tally', to='skitipp.Tipp')),
                ('tipper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_tally', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
