# Generated by Django 2.2.1 on 2019-09-19 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skitipp', '0011_pointadjustment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointadjustment',
            name='reason',
            field=models.CharField(max_length=200),
        ),
    ]
