# Generated by Django 2.2.1 on 2019-09-19 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skitipp', '0012_auto_20190919_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointadjustment',
            name='preseason',
            field=models.BooleanField(default=False),
        ),
    ]
