# Generated by Django 2.2.1 on 2019-09-19 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skitipp', '0013_pointadjustment_preseason'),
    ]

    operations = [
        migrations.AddField(
            model_name='raceevent',
            name='start_list_length',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tipppointtally',
            name='race_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='race_points_tally', to='skitipp.RaceEvent'),
        ),
        migrations.AlterField(
            model_name='tipppointtally',
            name='tipp',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tipp_points_tally', to='skitipp.Tipp'),
        ),
        migrations.AlterField(
            model_name='tipppointtally',
            name='tipper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_points_tally', to=settings.AUTH_USER_MODEL),
        ),
    ]
