# Generated by Django 2.2.1 on 2019-09-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skitipp', '0014_auto_20190919_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipppointtally',
            name='bonus_points',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tipppointtally',
            name='points_multiplier',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tipppointtally',
            name='standard_points',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='tipppointtally',
            name='total_points',
            field=models.FloatField(default=0),
        ),
    ]
