# Generated by Django 2.2.1 on 2019-09-20 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skitipp', '0015_auto_20190920_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipppointtally',
            name='tipp',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipp_points_tally', to='skitipp.Tipp'),
        ),
    ]
