# Generated by Django 2.2.1 on 2019-10-23 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skitipp', '0017_tipppointtally_is_best_tipp'),
    ]

    operations = [
        migrations.AddField(
            model_name='racer',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='racer',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
