# Generated by Django 2.2.1 on 2019-12-01 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skitipp', '0018_auto_20191023_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='raceevent',
            name='in_progress',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='raceevent',
            name='kind',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='raceevent',
            name='location',
            field=models.CharField(max_length=200),
        ),
    ]
