# Generated by Django 2.2.1 on 2020-01-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skitipp', '0019_auto_20191201_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipp',
            name='corrected_tipp',
            field=models.BooleanField(default=False),
        ),
    ]
