# Generated by Django 3.1.2 on 2020-12-20 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

from datetime import date


def populate_seasons(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Season = apps.get_model('skitipp', 'Season')
    s19 = Season(name='2019/2020', start_date = date(2019,10,1), end_date=date(2020,5,1))
    s19.save()
    s20 = Season(name='2020/2021', start_date = date(2020,10,1), end_date=date(2021,5,1))
    s20.save()

    RaceEvent = apps.get_model('skitipp', 'RaceEvent')
    for race_event in RaceEvent.objects.all():
        race_event.season = Season.objects.filter(
            start_date__lte=race_event.race_date,
            end_date__gte=race_event.race_date).first()
        race_event.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skitipp', '0020_tipp_corrected_tipp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('tippers', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='raceevent',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='races', to='skitipp.season'),
        ),
        migrations.RunPython(populate_seasons),
    ]
