# Generated by Django 3.1.2 on 2020-12-20 11:04

from django.db import migrations, models

def select_current_season(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Season = apps.get_model('skitipp', 'Season')
    s = Season.objects.all().last()
    s.current = True
    s.save()

class Migration(migrations.Migration):

    dependencies = [
        ('skitipp', '0021_auto_20201220_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='current',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(select_current_season)
    ]
