# Generated by Django 3.1.2 on 2020-12-20 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skitipp', '0022_season_current'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointadjustment',
            name='season',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='points_adjustments', to='skitipp.season'),
            preserve_default=False,
        ),
    ]
