# Generated by Django 3.2.8 on 2021-10-11 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skitipp', '0023_pointadjustment_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='fis_calendar',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
