# Generated by Django 3.2.8 on 2021-10-15 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skitipp', '0024_season_fis_calendar'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentReminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_on', models.DateTimeField(auto_now_add=True)),
                ('race_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_reminders', to='skitipp.raceevent')),
                ('tipper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_reminders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
