# Generated by Django 3.2.8 on 2021-12-17 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skitipp', '0026_tipper'),
    ]

    operations = [
        migrations.AddField(
            model_name='raceevent',
            name='is_classic',
            field=models.BooleanField(default=False),
        ),
    ]
