# Generated by Django 3.2.8 on 2021-12-17 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skitipp', '0027_raceevent_is_classic'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointadjustment',
            name='applicable_to',
            field=models.CharField(choices=[('Both', 'Both'), ('Overall', 'Overall'), ('Disciplines', 'Disciplines')], default='Both', max_length=20),
        ),
    ]
