# Generated by Django 4.2.18 on 2025-03-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skitipp', '0028_pointadjustment_applicable_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raceevent',
            name='kind',
            field=models.CharField(choices=[('Slalom', 'Slalom'), ('Giant Slalom', 'Giant Slalom'), ('Super G', 'Super G'), ('Downhill', 'Downhill'), ('Alpine Combined', 'Alpine Combined'), ('Team Combined', 'Team Combined')], max_length=200),
        ),
    ]
